services:
  db:
    image: postgres
    container_name: confeitaria-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: confeitaria_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: confeitaria-app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/confeitaria_development
    ports:
      - "3000:3000"
    volumes:
      - .:/app

volumes:
  postgres_data:
